---
- name: install some softweares
  hosts: webservers
  remote_user: devopsvince
  become: yes
  
  roles:
  - installer

- name: enable ssh without passwd
  hosts: webservers
  remote_user: devopsvince
  
  roles:
  - sshinit
